Discovered art page
Waidhoferj/CSC-308-309-Project pull request #31
Opened 2021-03-03 19:49 UTC by gwholland3

## Summary
Added UI elements to mirror the Framer mockup, visit the page `artwork/1` to view. Also changed some overarching styling.

## Todo
Still missing the scrolling pictures, and button functionality.

2021-03-03 19:52 UTC, gwholland3 commented
Fixes #25.

2021-03-03 21:04 UTC, Waidhoferj requested changes
There are a few style changes that are cascading across the project. Did you mean to make these changes?

2021-03-03 21:04 UTC, Waidhoferj commented on frontend/src/components/Tag/Tag.scss
> +  padding: 4px 17px;
I'm not so sure about these changes. At minimum we should have a larger margin between the Tag elements. Check out the map page which uses the Tag component. The elements are too close together.

2021-03-03 21:04 UTC, Waidhoferj commented on frontend/src/index.css
> +  --c-primary: #32A5ff;
Why are we changing the primary color here?

2021-03-03 23:29 UTC, gwholland3 commented
> There are a few style changes that are cascading across the project. Did you mean to make these changes?

Yeah I was just trying to get it to look almost identical to the tags in the Framer mockup. Should I keep them the way they're styled globally? Or is there an easy way to apply those changes just to the tags (and buttons in the case of the color) on the discovered art page?

2021-03-04 02:40 UTC, Waidhoferj commented
<img width="100" alt="Screen Shot 2021-03-03 at 6 36 36 PM" src="https://user-images.githubusercontent.com/33008436/109902839-d3a50500-7c4f-11eb-8bd8-e476e25bc314.png">
<img width="359" alt="Screen Shot 2021-03-03 at 6 38 49 PM" src="https://user-images.githubusercontent.com/33008436/109902842-d4d63200-7c4f-11eb-83ef-93a019cda355.png">
@gwholland3 I think the original dimensions were closer to the ground truth

2021-03-04 03:16 UTC, gwholland3 commented
Ok I'll restore them 👍

2021-03-04 19:13 UTC, gwholland3 commented
Ok so I was resetting most of the css properties, but I feel like at the very least a font size of 13 pixels is too small, and the font weight should probably be 500, since at 600 the letters are basically the same thickness as the border. Font size of 16 or 17 makes the relative sizing look more like the mockup imo.

2021-03-04 23:57 UTC, Waidhoferj commented
That works great! Good call!

2021-03-05 04:28 UTC, kyleshare approved these changes
Looks good

2021-03-05 04:44 UTC, Waidhoferj approved these changes
Looks good

2021-03-05 04:47 UTC, Waidhoferj commented
The branch is gonna need a rebase, it's all set once that's been done

2021-03-05 06:07 UTC, gwholland3 commented
@Waidhoferj What do you mean? Isn't it going to get merged into main?

2021-03-05 06:22 UTC, Waidhoferj commented
Yeah I mean you have to resolve your merge conflicts. Usually you rebase and ensure everything works still and then do a clean merge.

2021-03-05 06:43 UTC, Braden50 approved these changes
All looks great!

2021-03-05 19:39 UTC, merged